'use client';
import {useState,useEffect} from 'react';
import {QrCode,ShieldCheck,RefreshCw,Share2} from 'lucide-react';
import {api,authenticatedBlob,shareLink} from '@/lib/api';
import type {Church,Member,Report,Kind} from '@/lib/types';
import {Field,Check,Form,val} from './ui';
export function Admin({church,onRefresh,onToast,onOpen}:{church:Church;onRefresh:()=>Promise<void>;onToast:(s:string)=>void;onOpen:(kind:Kind,id:string)=>void}){
 const [members,setMembers]=useState<Member[]>([]),[reports,setReports]=useState<Report[]>([]),[invitation,setInvitation]=useState<{code:string;url:string}|null>(null),[qr,setQr]=useState(''),[approval,setApproval]=useState(church.require_approval),[error,setError]=useState(''),[filter,setFilter]=useState('pending');
 async function load(){try{const [m,r,i]=await Promise.all([api<Member[]>(`/churches/${church.id}/members`),api<Report[]>(`/churches/${church.id}/reports`),api<{code:string;url:string}>(`/churches/${church.id}/invitation`)]);setMembers(m);setReports(r);setInvitation(i);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load.')}}
 useEffect(()=>{void load()},[church.id]);
 useEffect(()=>{let active=true,url='';authenticatedBlob(`/churches/${church.id}/qr`).then(blob=>{url=URL.createObjectURL(blob);if(active)setQr(url)}).catch(()=>{});return()=>{active=false;if(url)URL.revokeObjectURL(url)}},[church.id,invitation?.code]);
 async function update(m:Member,status:Member['status'],role:'member'|'admin'='member'){try{await api(`/churches/${church.id}/members/${m.id}`,'PUT',{status,role});await load();onToast('Membership updated.')}catch(e){onToast(e instanceof Error?e.message:'Unable to update.')}}
 return <>{error&&<div className="error">{error}</div>}<div className="admin-grid"><section className="panel"><h2><QrCode size={22}/> Welcome people in.</h2><p>Share this code or QR code through your church’s trusted channels. Each church has its own invitation.</p>{invitation&&<><div className="invite-code">{invitation.code.match(/.{1,4}/g)?.join('-')}</div>{qr&&<img className="qr" src={qr} alt="QR code for joining this church"/>}<div className="row"><button className="primary" onClick={async()=>{try{onToast(await shareLink(invitation.url,`Join ${church.name} on Village`))}catch(e){onToast(e instanceof Error?e.message:'Unable to share.')}}}><Share2 size={16}/> Share invitation</button><a className="secondary" href={qr} download="village-church-qr.png">Download QR</a></div><p className="subtle break">{invitation.url}</p><button className="text-button" onClick={async()=>{if(confirm('Replace the access code? Existing members remain connected. Old QR codes and links will stop working.')){try{const i=await api<{code:string;url:string}>(`/churches/${church.id}/rotate-code`,'POST');setInvitation(i);onToast('Invitation replaced. Share the new code.')}catch(e){onToast(e instanceof Error?e.message:'Unable to replace.')}}}}><RefreshCw size={15}/> Replace code</button></>}</section>
 <section className="panel"><h2><ShieldCheck size={22}/> Church settings</h2><Form submit="Save church settings" onSubmit={async data=>{await api(`/churches/${church.id}`,'PUT',{name:val(data,'name'),location:val(data,'location'),timezone:val(data,'timezone'),require_approval:approval});await onRefresh();onToast('Church settings saved.')}}><Field label="Church name"><input name="name" required defaultValue={church.name} maxLength={150}/></Field><Field label="City / location"><input name="location" defaultValue={church.location} maxLength={200}/></Field><Field label="Timezone"><input name="timezone" required defaultValue={church.timezone}/></Field><p className="subtle">Invitation links, QR codes, and invitation codes connect members directly. Requests through church search always need administrator approval.</p></Form></section></div>
 <section className="panel"><div className="section-line"><h2>Your church family</h2><button className="secondary" onClick={()=>void load()}>Refresh</button></div><div className="tabs">{['pending','approved','removed','all'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f==='pending'?`Requests (${members.filter(m=>m.status==='pending').length})`:f[0].toUpperCase()+f.slice(1)}</button>)}</div>{members.filter(m=>filter==='all'||m.status===filter).map(m=><div className="member-admin" key={m.id}><div><strong>{m.name}</strong><small>{m.email} · {m.role} · {m.status}</small></div><div className="row">{m.status==='pending'&&<button className="primary" onClick={()=>void update(m,'approved')}>Approve</button>}{m.role!=='owner'&&<><button className="text-button danger" onClick={()=>{if(confirm(`Remove ${m.name} from this church? They will lose access and their upcoming commitments will be released.`))void update(m,'removed',m.role==='admin'?'admin':'member')}}>Remove access</button>{church.role==='owner'&&m.status==='approved'&&<><button className="text-button" onClick={()=>{if(confirm(`Change ${m.name} to ${m.role==='admin'?'member':'admin'}?`))void update(m,'approved',m.role==='admin'?'member':'admin')}}>{m.role==='admin'?'Make member':'Make admin'}</button><button className="text-button" onClick={async()=>{if(confirm(`Transfer church ownership to ${m.name}? You will remain an admin.`)){try{await api(`/churches/${church.id}/transfer/${m.id}`,'POST');await onRefresh();await load()}catch(e){onToast(e instanceof Error?e.message:'Unable to transfer.')}}}}>Transfer ownership</button></>}</>}</div></div>)}{!members.some(m=>filter==='all'||m.status===filter)&&<p className="subtle">No members in this view.</p>}</section>
 <section className="panel"><h2>Community concerns</h2><p className="subtle">Review reports promptly. Remove harmful content or suspend access when needed, then mark the report resolved.</p>{reports.filter(r=>!r.resolved).map(r=><article className="report" key={r.id}><span className="eyebrow">{r.kind}</span><p>{r.reason}</p><small>{new Date(r.created_at).toLocaleString()} · {r.target_id}</small><div className="row">{['events','needs','meals'].includes(r.kind)&&<button className="secondary" onClick={()=>onOpen(r.kind as Kind,r.target_id)}>Review content</button>}{r.kind==='comments'&&<button className="text-button danger" onClick={async()=>{if(confirm('Remove this reported comment?')){try{await api(`/churches/${church.id}/comments/${r.target_id}`,'DELETE');onToast('Comment removed.')}catch(e){onToast(e instanceof Error?e.message:'Unable to remove.')}}}}>Remove comment</button>}<button className="text-button" onClick={async()=>{try{await api(`/churches/${church.id}/reports/${r.id}/resolve`,'POST');await load()}catch(e){onToast(e instanceof Error?e.message:'Unable to resolve.')}}}>Mark resolved</button></div></article>)}{!reports.some(r=>!r.resolved)&&<p>No open reports.</p>}</section>
 {church.role==='owner'&&<section className="panel"><details><summary>Delete church community</summary><p>This permanently deletes the church directory connections, posts, and meal trains. Member accounts remain.</p><button className="secondary danger" onClick={async()=>{if(prompt('Type the church name to permanently delete it:')===church.name){try{await api(`/churches/${church.id}`,'DELETE');await onRefresh()}catch(e){onToast(e instanceof Error?e.message:'Unable to delete.')}}}}>Delete {church.name}</button></details></section>}</>
}
