'use client';
import {useState,useEffect,useRef} from 'react';
import {Heart,ShieldCheck,QrCode,ArrowLeft} from 'lucide-react';
import {api,native,storeSession,scanInvitation} from '@/lib/api';
import type {Person,Church} from '@/lib/types';
import {Brand,Field,Check,Form,val} from './ui';
export function Auth({onLogin,invite,onClearInvite}:{onClearInvite?:()=>void;onLogin:(u:Person,onboarding?:boolean)=>void;invite:string}){
 const [mode,setMode]=useState(invite?'register':'login'),[message,setMessage]=useState(''),[terms,setTerms]=useState(false),[token,setToken]=useState('');
 const [email,setEmail]=useState('');
 const verifyPromise=useRef<Promise<{user:Person;token?:string;message:string}>|null>(null);
 useEffect(()=>{let active=true;const p=new URLSearchParams(location.search);
  if(p.get('action')==='reset'){setMode('reset');setToken(p.get('token')||'')}
  if(p.get('action')==='verify'){
   setMessage('Confirming your email…');
   if(!verifyPromise.current)verifyPromise.current=api('/auth/verify','POST',{token:p.get('token'),native:native()});
   verifyPromise.current.then(async r=>{if(!active)return;await storeSession(r.token);history.replaceState(null,'','/?view=profile');onLogin(r.user,true)}).catch(e=>{if(active){setMode('login');setMessage(e.message)}});
  }
  return()=>{active=false};
 },[]);
 return <main className="auth-layout"><div className="auth-story"><Brand/><span className="eyebrow">A little closer. A little more connected.</span><h1>Church family.<br/><em>Every day of the week.</em></h1><p>A place to know one another, make room at the table, and show up when it matters.</p><div className="story-notes"><span><Heart size={18}/> Everyday invitations</span><span><ShieldCheck size={18}/> Private to your church</span></div></div><section className="auth-panel"><span className="eyebrow">Welcome to Village</span><h2>{mode==='register'?'Make yourself at home.':mode==='login'?'Good to see you.':mode==='reset'?'A fresh start.':'Let’s get you back in.'}</h2><p>{invite?'Your church invitation is saved. Sign in or create an account to join.':'A shared place for a life shared.'}</p>{invite&&onClearInvite&&<button className="text-button" type="button" onClick={onClearInvite}>Continue without this invitation</button>}{message&&<p role="status" className="success">{message}</p>}
 <Form key={mode} submit={mode==='register'?'Create account':mode==='login'?'Sign in':mode==='reset'?'Update password':'Send email link'} onSubmit={async data=>{
   if(mode==='login'){const result=await api<{user:Person;token?:string}>('/auth/login','POST',{email:val(data,'email'),password:val(data,'password'),native:native()});await storeSession(result.token);onLogin(result.user,sessionStorage.getItem('village-onboarding-email')===val(data,'email').toLowerCase())}
   else if(mode==='register'){const result=await api<{message:string;user?:Person;token?:string}>('/auth/register','POST',{email:val(data,'email'),password:val(data,'password'),name:val(data,'name'),accept_terms:terms,invite_code:invite,native:native()});sessionStorage.setItem('village-onboarding-email',val(data,'email').toLowerCase());if(result.user){await storeSession(result.token);onLogin(result.user,true)}else{setMessage(result.message);setMode('login')}}
   else if(mode==='reset'){const result=await api<{message:string}>('/auth/reset','POST',{token,password:val(data,'password')});setMessage(result.message);setMode('login');history.replaceState(null,'','/')}
   else {const result=await api<{message:string}>(mode==='resend'?'/auth/resend-verification':'/auth/forgot-password','POST',{email:val(data,'email')});setMessage(result.message)}
 }}>
 {mode==='register'&&<Field label="Your name"><input name="name" autoComplete="name" required maxLength={120}/></Field>}
 {mode!=='reset'&&<Field label="Email address"><input name="email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></Field>}
 {['login','register','reset'].includes(mode)&&<Field label="Password" hint={mode==='login'?undefined:'At least 12 characters. A memorable phrase works well.'}><input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?1:12} maxLength={256} required/></Field>}
 {mode==='register'&&<><Check label="I agree to respect this community and its privacy." checked={terms} onChange={setTerms}/><small>By creating an account you accept our <a href="/terms.html" target="_blank" rel="noreferrer">community terms</a> and <a href="/privacy.html" target="_blank" rel="noreferrer">privacy policy</a>. This account is for adults.</small></>}
 </Form><div className="auth-links"><button onClick={()=>{setMode(mode==='register'?'login':'register');setMessage('')}}>{mode==='register'?'Already a member? Sign in':'New here? Create an account'}</button><button onClick={()=>{setMode('forgot');setMessage('')}}>Forgot password?</button><button onClick={()=>{setMode('resend');setMessage('')}}>Resend verification</button></div></section></main>
}
export function JoinChurch({churches,invite,onRefresh,onSelect}:{churches:Church[];invite:string;onRefresh:()=>Promise<void>;onSelect:(id:string)=>void}){
 const [mode,setMode]=useState('join'),[code,setCode]=useState(invite),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[results,setResults]=useState<{id:string;name:string;location:string;status:string|null}[]>([]),[busy,setBusy]=useState(false);
 useEffect(()=>{if(invite)setCode(invite)},[invite]);
 async function join(value:string){const c=await api<Church>('/churches/join','POST',{code:value});setMessage('You’re connected!');await onRefresh();onSelect(c.id)}
 async function request(id:string){setBusy(true);try{const c=await api<Church>(`/churches/${id}/request-membership`,'POST');setMessage(c.status==='approved'?'You’re already connected.':'Request sent. Your church team will approve your access.');setResults(rows=>rows.map(r=>r.id===id?{...r,status:c.status}:r));await onRefresh();if(c.status==='approved')onSelect(c.id)}catch(e){setMessage(e instanceof Error?e.message:'Unable to send request.')}finally{setBusy(false)}}
 return <div className="narrow"><div className="page-heading"><span className="eyebrow">Find your people</span><h1>Welcome to your Village.</h1><p>An invitation or QR code connects you right away. Searching for a church sends a request to its team.</p></div>
 {churches.map(c=><div className="panel" key={c.id}><h3>{c.name}</h3><p>{c.status==='pending'?'Your request is with the church team. Have an invitation? Enter its code below to connect right away.':c.status==='removed'?'Please contact your church administrator.':'You’re connected.'}</p>{c.status==='approved'&&<button className="primary" onClick={()=>onSelect(c.id)}>Open your church</button>}</div>)}
 {message&&<p role="status">{message}</p>}
 <section className="panel"><div className="tabs"><button className={mode==='join'?'active':''} onClick={()=>setMode('join')}>I have an invitation</button><button className={mode==='search'?'active':''} onClick={()=>setMode('search')}>Find my church</button><button className={mode==='create'?'active':''} onClick={()=>setMode('create')}>Set up a church</button></div>
 {mode==='join'?<Form submit="Connect to my church" onSubmit={async()=>join(code)}><Field label="Church invitation code"><input value={code} onChange={e=>setCode(e.target.value)} required placeholder="e.g. ABCD-EFGH-JKLM" autoCapitalize="characters"/></Field><button type="button" className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const value=await scanInvitation();setCode(value);await join(value)}catch(e){setMessage(e instanceof Error?e.message:'Camera unavailable. Enter the code instead.')}finally{setBusy(false)}}}><QrCode size={18}/> Scan a QR code</button><p className="subtle">You can also scan your church’s QR code with your phone’s camera. No app download is required to join on the website.</p></Form>:mode==='search'?<><Form submit="Search churches" onSubmit={async()=>{const rows=await api<{id:string;name:string;location:string;status:string|null}[]>('/churches/search?q='+encodeURIComponent(query));setResults(rows);setMessage(rows.length?'Select your church to request membership.':'No matching churches. Ask your church team for an invitation.')}}><Field label="Church name or city"><input value={query} onChange={e=>setQuery(e.target.value)} required minLength={2} maxLength={100}/></Field></Form>{results.map(c=><div className="panel" key={c.id}><h3>{c.name}</h3><p>{c.location}</p><button className="secondary" disabled={busy||c.status==='pending'||c.status==='removed'} onClick={()=>c.status==='approved'?onSelect(c.id):void request(c.id)}>{c.status==='approved'?'Open church':c.status==='pending'?'Awaiting approval':c.status==='removed'?'Contact church team':'Request to join'}</button></div>)}</>:
 <Form submit="Create church community" onSubmit={async data=>{const c=await api<Church>('/churches','POST',{name:val(data,'name'),location:val(data,'location'),timezone:val(data,'timezone'),require_approval:true});await onRefresh();onSelect(c.id)}}><p>For church staff or someone setting this up with the church’s permission. You’ll become its administrator. People with an invitation join directly; search requests need approval.</p><Field label="Church name"><input name="name" required minLength={2} maxLength={150}/></Field><Field label="City / location"><input name="location" maxLength={200}/></Field><Field label="Church timezone"><input name="timezone" defaultValue="America/New_York" required/></Field></Form>}
 </section>{churches.some(c=>c.status==='pending')&&<button className="secondary" onClick={()=>void onRefresh()}>Check approval status</button>}</div>
}
