'use client';
import {useState,useEffect} from 'react';
import {Heart,ShieldCheck,QrCode,ArrowLeft} from 'lucide-react';
import {api,native,storeSession,scanInvitation} from '@/lib/api';
import type {Person,Church} from '@/lib/types';
import {Brand,Field,Check,Form,val} from './ui';
export function Auth({onLogin,invite}:{onLogin:(u:Person)=>void;invite:string}){
 const [mode,setMode]=useState('login'),[message,setMessage]=useState(''),[terms,setTerms]=useState(false),[token,setToken]=useState('');
 useEffect(()=>{const p=new URLSearchParams(location.search);if(p.get('action')==='reset'){setMode('reset');setToken(p.get('token')||'')}if(p.get('action')==='verify'){api<{message:string}>('/auth/verify','POST',{token:p.get('token')}).then(r=>{setMessage(r.message);history.replaceState(null,'','/')}).catch(e=>setMessage(e.message))}},[]);
 return <main className="auth-layout"><div className="auth-story"><Brand/><span className="eyebrow">A little closer. A little more connected.</span><h1>Church family.<br/><em>Every day of the week.</em></h1><p>A place to know one another, make room at the table, and show up when it matters.</p><div className="story-notes"><span><Heart size={18}/> Everyday invitations</span><span><ShieldCheck size={18}/> Private to your church</span></div></div><section className="auth-panel"><span className="eyebrow">Welcome to Village</span><h2>{mode==='register'?'Make yourself at home.':mode==='login'?'Good to see you.':mode==='reset'?'A fresh start.':'Let’s get you back in.'}</h2><p>{invite?'Your church invitation is saved. Sign in or create an account to join.':'A shared place for a life shared.'}</p>{message&&<p role="status" className="success">{message}</p>}
 <Form key={mode} submit={mode==='register'?'Create account':mode==='login'?'Sign in':mode==='reset'?'Update password':'Send email link'} onSubmit={async data=>{
   if(mode==='login'){const result=await api<{user:Person;token?:string}>('/auth/login','POST',{email:val(data,'email'),password:val(data,'password'),native:native()});await storeSession(result.token);onLogin(result.user)}
   else if(mode==='register'){const result=await api<{message:string}>('/auth/register','POST',{email:val(data,'email'),password:val(data,'password'),name:val(data,'name'),accept_terms:terms});setMessage(result.message);setMode('login')}
   else if(mode==='reset'){const result=await api<{message:string}>('/auth/reset','POST',{token,password:val(data,'password')});setMessage(result.message);setMode('login');history.replaceState(null,'','/')}
   else {const result=await api<{message:string}>(mode==='resend'?'/auth/resend-verification':'/auth/forgot-password','POST',{email:val(data,'email')});setMessage(result.message)}
 }}>
 {mode==='register'&&<Field label="Your name"><input name="name" autoComplete="name" required maxLength={120}/></Field>}
 {mode!=='reset'&&<Field label="Email address"><input name="email" type="email" autoComplete="email" required/></Field>}
 {['login','register','reset'].includes(mode)&&<Field label="Password" hint={mode==='login'?undefined:'At least 12 characters. A memorable phrase works well.'}><input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?1:12} maxLength={256} required/></Field>}
 {mode==='register'&&<><Check label="I agree to respect this community and its privacy." checked={terms} onChange={setTerms}/><small>By creating an account you accept our <a href="/terms.html" target="_blank" rel="noreferrer">community terms</a> and <a href="/privacy.html" target="_blank" rel="noreferrer">privacy policy</a>. This account is for adults.</small></>}
 </Form><div className="auth-links"><button onClick={()=>{setMode(mode==='register'?'login':'register');setMessage('')}}>{mode==='register'?'Already a member? Sign in':'New here? Create an account'}</button><button onClick={()=>{setMode('forgot');setMessage('')}}>Forgot password?</button><button onClick={()=>{setMode('resend');setMessage('')}}>Resend verification</button></div></section></main>
}
export function JoinChurch({churches,invite,onRefresh,onSelect}:{churches:Church[];invite:string;onRefresh:()=>Promise<void>;onSelect:(id:string)=>void}){
 const [mode,setMode]=useState('join'),[code,setCode]=useState(invite),[message,setMessage]=useState(''),[approval,setApproval]=useState(true);
 return <div className="narrow"><div className="page-heading"><span className="eyebrow">Find your people</span><h1>Welcome to your Village.</h1><p>Your church’s code or invitation connects you to its private community.</p></div>
 {churches.map(c=><div className="panel" key={c.id}><h3>{c.name}</h3><p>{c.status==='pending'?'Your request is with the church team. You’ll be able to see the community once they approve you.':c.status==='removed'?'Please contact your church administrator.':'You’re connected.'}</p>{c.status==='approved'&&<button className="primary" onClick={()=>onSelect(c.id)}>Open your church</button>}</div>)}
 {message&&<p className="success" role="status">{message}</p>}
 <section className="panel"><div className="tabs"><button className={mode==='join'?'active':''} onClick={()=>setMode('join')}>Join a church</button><button className={mode==='create'?'active':''} onClick={()=>setMode('create')}>Set up a church</button></div>
 {mode==='join'?<Form submit="Join my church" onSubmit={async()=>{const c=await api<Church>('/churches/join','POST',{code});setMessage(c.status==='pending'?'Request sent. Your church team will approve your access.':'You’re connected!');await onRefresh();if(c.status==='approved')onSelect(c.id)}}><Field label="Church access code"><input value={code} onChange={e=>setCode(e.target.value)} required placeholder="e.g. ABCD-EFGH-JKLM" autoCapitalize="characters"/></Field><button type="button" className="secondary" onClick={async()=>{try{setCode(await scanInvitation())}catch(e){setMessage(e instanceof Error?e.message:'Camera unavailable. Enter the code instead.')}}}><QrCode size={18}/> Scan a QR code</button><p className="subtle">You can also scan your church’s QR code with your phone’s camera and open its invitation link.</p></Form>:
 <Form submit="Create church community" onSubmit={async data=>{const c=await api<Church>('/churches','POST',{name:val(data,'name'),location:val(data,'location'),timezone:val(data,'timezone'),require_approval:approval});await onRefresh();onSelect(c.id)}}><p>For church staff or someone setting this up with the church’s permission. You’ll become its administrator.</p><Field label="Church name"><input name="name" required minLength={2} maxLength={150}/></Field><Field label="City / location"><input name="location" maxLength={200}/></Field><Field label="Church timezone"><input name="timezone" defaultValue="America/New_York" required/></Field><Check label="Approve new members before they can see private information" checked={approval} onChange={setApproval}/></Form>}
 </section>{churches.some(c=>c.status==='pending')&&<button className="secondary" onClick={()=>void onRefresh()}>Check approval status</button>}</div>
}
