'use client';
import {useState,useEffect} from 'react';
import {CalendarDays,HandHeart,Utensils,MapPin,ArrowRight,Share2,MessageCircle,CheckCircle,Users,ShieldCheck} from 'lucide-react';
import {api,shareLink} from '@/lib/api';
import type {Item,Kind,Church,Person,ChurchEvent,Need,MealTrain,MealSlot,Comment} from '@/lib/types';
import {calendarDate,eventDate,calendarFile} from '@/lib/dates';
import {Empty,Form,Field,Avatar,Modal,val,num} from './ui';
const icons={events:CalendarDays,needs:HandHeart,meals:Utensils};
export function ItemCard({kind,item,church,onOpen}:{kind:Kind;item:Item;church:Church;onOpen:()=>void}) {
 const e=item as ChurchEvent,n=item as Need,t=item as MealTrain,Icon=icons[kind];
 return <button className={`item-card ${kind}`} onClick={onOpen}><div className="card-top"><span className="type-label"><Icon size={17}/>{kind==='events'?(e.official?'Church invitation':'Life together'):kind==='needs'?n.category:'Around the table'}</span><span className="card-arrow"><ArrowRight size={17}/></span></div><h3>{item.title}</h3><p className="description">{item.description||'Open to see the details and join in.'}</p>
 {kind==='events'?<><div className="card-meta"><CalendarDays size={15}/>{eventDate(e.starts_at,church.timezone)}</div><div className="card-meta"><MapPin size={15}/>{e.location||'See invitation for details'}</div><div className="card-bottom"><span>{e.attendee_count} going{e.capacity?` / ${e.capacity} places`:''}</span><strong>{e.cancelled?'Cancelled':e.my_rsvp?'You’re going':e.capacity&&e.attendee_count>=e.capacity?'Full':'Come along'}</strong></div></>:
 kind==='needs'?<><div className="card-meta"><Users size={15}/>{n.volunteer_count} of {n.volunteers_needed} helping</div>{n.due_date&&<div className="card-meta">By {calendarDate(n.due_date)}</div>}<div className="card-bottom"><span>{n.status==='fulfilled'?'Care, received.':n.status==='closed'?'Closed':`${Math.max(0,n.volunteers_needed-n.volunteer_count)} more welcome`}</span><strong>{n.my_volunteer?'You’re helping':'I can help'}</strong></div></>:
 <><div className="card-meta"><Utensils size={15}/>{t.adults} adults · {t.children} children</div><div className="card-meta">{calendarDate(t.start_date)} – {calendarDate(t.end_date)}</div><div className="card-bottom"><span>{t.claimed_count} of {t.slot_count} meals covered</span><strong>{t.closed?'Closed':t.my_count?'You’ve joined in':'Bring a meal'}</strong></div></>}
 </button>
}
export function Directory({people,onReport,onBlock}:{people:Person[];onReport:(id:string)=>void;onBlock:(id:string)=>void}){
 const [query,setQuery]=useState(''),[group,setGroup]=useState(''),[available,setAvailable]=useState(false),[expanded,setExpanded]=useState('');
 const groupOptions=[...new Set(people.flatMap(p=>p.groups||[]))].sort();
 const filtered=people.filter(p=>(!group||(p.groups||[]).includes(group))&&(!available||p.available)&&(!query||[p.name,p.bio,p.email,p.phone,p.address,p.household,...(p.skills||[]),...(p.resources||[])].join(' ').toLowerCase().includes(query.toLowerCase())));
 return <><div className="filters"><input type="search" aria-label="Search people, skills or resources" placeholder="A name, a truck, piano lessons…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Directory group" value={group} onChange={e=>setGroup(e.target.value)}><option value="">All groups</option>{groupOptions.map(g=><option key={g}>{g}</option>)}</select><label className="inline-check"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/> Available to help</label></div><p className="subtle">{filtered.length} people · Contact details appear only when someone chooses to share them.</p>
 <div className="directory-grid">{filtered.map(p=><article key={p.id} className="person-card"><div className="person-header"><Avatar name={p.name}/><div><h3>{p.name}</h3><small>{p.available?'Happy to lend a hand':'Get to know me'}</small></div></div>{p.bio&&<p>{p.bio}</p>}<div className="tags">{[...(p.skills||[]),...(p.resources||[])].map((s,i)=><span key={`${s}-${i}`}>{s}</span>)}</div>{p.groups?.length>0&&<small className="subtle">{p.groups.join(' · ')}</small>}
 <button className="text-button" onClick={()=>setExpanded(expanded===p.id?'':p.id)}>{expanded===p.id?'Less detail':'Contact & household'} <ArrowRight size={14}/></button>{expanded===p.id&&<div className="person-details">{p.household&&<p>{p.household}</p>}{p.phone&&<p><a href={`tel:${p.phone.replace(/[^+\d]/g,'')}`}>{p.phone}</a></p>}{p.email&&<p><a href={`mailto:${p.email}`}>{p.email}</a></p>}{p.address&&<p>{p.address}</p>}{!p.phone&&!p.email&&!p.address&&!p.household&&<p className="subtle">They’re keeping contact details private. Connect at church or through an invitation or need they’ve shared.</p>}<div className="row"><button className="text-button" onClick={()=>onReport(p.id)}>Report a concern</button><button className="text-button" onClick={()=>onBlock(p.id)}>Block member</button></div></div>}</article>)}</div>
 {!filtered.length&&<Empty title="A place to find each other" text="Try a different search, or add your own skills and resources in Settings."/>}</>
}
export function Detail({kind,item,church,user,onEdit,onDelete,onRefresh,onReport,onToast}:{kind:Kind;item:Item;church:Church;user:Person;onEdit:()=>void;onDelete:()=>void;onRefresh:()=>Promise<void>;onReport:(kind:Kind|'comments',id:string)=>void;onToast:(message:string)=>void}) {
 const [comments,setComments]=useState<Comment[]>([]),[slot,setSlot]=useState<MealSlot|null>(null),[bookFor,setBookFor]=useState(''),[members,setMembers]=useState<{id:string;name:string}[]>([]),[commentKey,setCommentKey]=useState(0),[commentError,setCommentError]=useState('');
 const e=item as ChurchEvent,n=item as Need,t=item as MealTrain;
 const root=`/churches/${church.id}/${kind}/${item.id}`;
 useEffect(()=>{let active=true;api<Comment[]>(root+'/comments').then(r=>{if(active){setComments(r);setCommentError('')}}).catch(err=>{if(active)setCommentError(err.message)});return()=>{active=false}},[root,commentKey]);
 useEffect(()=>{if(kind==='meals'&&t.can_manage)api<Person[]>(`/churches/${church.id}/directory`).then(setMembers).catch(()=>setMembers([]))},[kind,church.id,t.can_manage]);
 useEffect(()=>{if(slot)setSlot((t.slots||[]).find(s=>s.id===slot.id)||null)},[t.slots]);
 async function action(path:string,method:string,data?:unknown){await api(root+path,method,data);await onRefresh()}
 async function simple(path:string,method:string,data?:unknown){try{await action(path,method,data)}catch(error){onToast(error instanceof Error?error.message:'Please try again.')}}
 return <div className="detail"><div className="detail-top"><span className="eyebrow">{kind==='meals'?'A little care, delivered':kind==='needs'?'Show up for one another':'There’s room for you'}</span><button className="secondary" onClick={async()=>{try{const origin=process.env.NEXT_PUBLIC_WEB_URL||location.origin;onToast(await shareLink(`${origin}/?view=${kind}&id=${item.id}&church=${church.id}`,item.title))}catch(err){onToast(err instanceof Error?err.message:'Unable to share.')}}}><Share2 size={16}/> Share</button></div><h1>{item.title}</h1><p className="organizer">Organized by {item.organizer}</p><p className="long-text">{item.description}</p>
 {item.can_manage&&<div className="row"><button className="secondary" onClick={onEdit}>Edit details</button><button className="text-button danger" onClick={onDelete}>Delete</button></div>}
 {kind==='events'&&<><section className="panel"><div className="facts"><div><CalendarDays/><span>{eventDate(e.starts_at,church.timezone)}{e.ends_at&&<> – {eventDate(e.ends_at,church.timezone)}</>}<small>{church.timezone}</small></span></div><div><MapPin/><span>{e.location||'Contact the host for the location.'}</span></div><div><Users/><span>{e.attendee_count} people going{e.capacity?` · ${Math.max(0,e.capacity-e.attendee_count)} places left`:''}</span></div></div><div className="tags">{e.audience.map(a=><span key={a}>{a}</span>)}{e.official&&<span>Official church event</span>}</div></section>
 {e.cancelled?<p className="error">This event has been cancelled.</p>:new Date(e.starts_at)<new Date()?<p className="subtle">This invitation is in the past.</p>:<section className="panel"><h3>{e.my_rsvp?'You’re on the list.':'Come along.'}</h3><Form key={e.my_rsvp?.guest_count+':'+e.my_rsvp?.note} submit={e.my_rsvp?'Update RSVP':'Count me in'} onSubmit={async data=>action('/rsvp','PUT',{guest_count:num(data,'guests'),note:val(data,'note')})}><Field label="Additional guests" hint="Your RSVP already includes you. Add your spouse, children, or other guests here."><input type="number" name="guests" min={0} max={30} defaultValue={e.my_rsvp?.guest_count||0}/></Field><Field label="Note for the host (optional)"><input name="note" maxLength={500} defaultValue={e.my_rsvp?.note||''}/></Field></Form>{e.my_rsvp&&<button className="text-button danger" onClick={()=>void simple('/rsvp','DELETE')}>Cancel my RSVP</button>}<button className="text-button" onClick={async()=>{try{await calendarFile(e.title,e.starts_at,e.ends_at||undefined,e.description,e.location)}catch(err){onToast(err instanceof Error?err.message:'Unable to export calendar event.')}}}>Add to my calendar</button></section>}
 <section className="panel"><h3>Who’s coming</h3>{e.attendees?.map((a,i)=><div className="member-row" key={i}><span>{a.name}{a.guest_count?` + ${a.guest_count}`:''}</span>{a.note&&<small>{a.note}</small>}</div>)}{!e.attendees?.length&&<p className="subtle">Be the first to join in.</p>}</section></>}
 {kind==='needs'&&<><section className="panel"><div className="tags"><span>{n.category}</span><span>{n.status}</span></div>{n.on_behalf&&<p>For {n.on_behalf}</p>}{n.location&&<p><MapPin size={16}/> {n.location}</p>}{n.due_date&&<p>Needed by {calendarDate(n.due_date,true)}</p>}<h3>{n.volunteer_count} of {n.volunteers_needed} people helping</h3></section>
 {n.status==='open'&&<section className="panel"><h3>{n.my_volunteer?'Thank you for showing up.':'Your help could make their day.'}</h3><Form submit={n.my_volunteer?'Update my offer':'I can help'} onSubmit={async data=>action('/volunteer','PUT',{note:val(data,'note')})}><Field label="Note for the organizer (optional)"><textarea name="note" maxLength={500} defaultValue={n.my_volunteer?.note||''} placeholder="I have a truck; I can come after 2…"/></Field></Form>{n.my_volunteer&&<button className="text-button danger" onClick={()=>void simple('/volunteer','DELETE')}>Cancel my offer</button>}</section>}
 <section className="panel"><h3>Helping hands</h3>{n.volunteers?.map((v,i)=><div className="member-row" key={i}><span>{v.name}</span>{v.note&&<small>{v.note}</small>}</div>)}{!n.volunteers?.length&&<p className="subtle">A chance to be the first helping hand.</p>}</section></>}
 {kind==='meals'&&<><section className="panel meal-info"><h3>Meals for {t.recipient}</h3><p>{t.adults} adults · {t.children} children · Delivery {t.delivery_window}</p>{t.allergies&&<div className="allergy"><ShieldCheck size={19}/><div><strong>Allergies & dietary needs</strong><p>{t.allergies}</p></div></div>}{t.preferences&&<><h4>What they enjoy</h4><p className="long-text">{t.preferences}</p></>}{t.address||t.can_manage||t.my_count?<><h4>Delivery details</h4><p>{t.address||'Contact the organizer for the address.'}</p><p>{t.contact}</p><p className="long-text">{t.instructions}</p></>:<p className="subtle">The address and delivery contact appear after you claim a meal date.</p>}<p className="subtle">Homemade, takeout, or a gift card can all be a kindness. Check the preferences and tell the family what you’re planning.</p></section>
 {t.closed&&<p className="error">This meal train is closed to new bookings.</p>}
 <div className="section-line"><h2>The meal calendar</h2><span>{t.claimed_count}/{t.slot_count} covered</span></div><p className="subtle">See what others are bringing, then choose an open date. Dates are shown in the church’s calendar ({church.timezone}).</p>
 <div className="meal-slots">{t.slots?.map(s=><article key={s.id} className={`meal-slot ${s.user_id?'claimed':''} ${s.user_id===user.id?'mine':''}`}><div className="slot-date"><strong>{calendarDate(s.date,true)}</strong>{s.delivered&&<span className="badge"><CheckCircle size={14}/> Delivered</span>}</div><div><strong>{s.user_id?s.name:'A meal would be lovely.'}</strong><p className="long-text">{s.user_id?s.meal:'This date is available.'}</p>{s.note&&<small>{s.note}</small>}</div><div className="slot-actions">{!s.user_id&&!t.closed&&<button className="primary" onClick={()=>{setSlot(s);setBookFor('')}}>Bring a meal</button>}{(s.user_id===user.id||(s.user_id&&t.can_manage))&&<><button className="secondary" onClick={()=>{setSlot(s);setBookFor(s.user_id===user.id?'':s.user_id||'')}}>Edit meal</button><button className="text-button" onClick={()=>void simple(`/slots/${s.id}/delivered`,'PUT',{delivered:!s.delivered})}>{s.delivered?'Unmark delivery':'Mark delivered'}</button>{!s.delivered&&<button className="text-button danger" onClick={()=>{if(confirm('Cancel this meal commitment and reopen the date?'))void simple(`/slots/${s.id}`,'DELETE')}}>Cancel booking</button>}</>}</div></article>)}</div>
 {slot&&<Modal title={calendarDate(slot.date,true)} onClose={()=>setSlot(null)}><section className="claim-form"><div className="section-line"><h3>{calendarDate(slot.date,true)}</h3><button className="text-button" onClick={()=>setSlot(null)}>Close</button></div><p>Delivery: {t.delivery_window} · {t.adults} adults + {t.children} children</p>{t.allergies&&<p className="allergy">Dietary needs: {t.allergies}</p>}<Form key={slot.id} submit={slot.user_id?'Save meal details':'Confirm my meal'} onSubmit={async data=>{await action(`/slots/${slot.id}`,'PUT',{meal:val(data,'meal'),note:val(data,'note'),...(bookFor?{for_user_id:bookFor,consent:data.get('permission')==='on'}:{})});setSlot(null);onToast('Meal date confirmed. Thank you for caring.') }}>
 {t.can_manage&&<Field label="Who is bringing this meal?"><select value={bookFor} onChange={e=>setBookFor(e.target.value)}><option value="">Me — {user.name}</option>{members.filter(m=>m.id!==user.id).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field>}{bookFor&&<label className="check"><input name="permission" type="checkbox" required/><span>This member gave permission to book for them.</span></label>}
 <Field label="What meal are you bringing?" hint="For example: chicken soup, rolls and fruit, or takeout from their favorite place."><textarea name="meal" required maxLength={1000} defaultValue={slot.meal}/></Field><Field label="Note for the organizer (optional)"><textarea name="note" maxLength={1000} defaultValue={slot.note}/></Field></Form></section></Modal>}
 </>}
 <section className="panel"><h3><MessageCircle size={19}/> Questions & updates</h3><p className="subtle">Keep the details here so no one needs another group chat. Approved church members can read updates. Keep private contact details in the delivery fields.</p>{commentError&&<p className="error">{commentError}</p>}{comments.map(c=><article className="comment" key={c.id}><div className="row"><Avatar name={c.name}/><strong>{c.name}</strong><small>{new Date(c.created_at).toLocaleDateString()}</small></div><p className="long-text">{c.text}</p><div className="row">{c.can_delete&&<button className="text-button danger" onClick={async()=>{try{await api(`/churches/${church.id}/comments/${c.id}`,'DELETE');setCommentKey(k=>k+1)}catch(err){onToast(err instanceof Error?err.message:'Unable to delete.')}}}>Delete</button>}<button className="text-button" onClick={()=>onReport('comments',c.id)}>Report</button></div></article>)}<Form key={commentKey} submit="Post update" onSubmit={async data=>{await api(root+'/comments','POST',{text:val(data,'text')});setCommentKey(k=>k+1)}}><Field label="Add a question, thanks, or update"><textarea name="text" required maxLength={2000}/></Field></Form></section><button className="text-button subtle" onClick={()=>onReport(kind,item.id)}>Report a concern</button>
 </div>
}
