'use client';
import {useState,useEffect} from 'react';
import {ShieldCheck,Bell,UserRound,Download} from 'lucide-react';
import type {Church,Person,Privacy,Preferences} from '@/lib/types';
import {api,native,enablePush,disablePush,storeSession} from '@/lib/api';
import {download} from '@/lib/dates';
import {Field,Check,Form,val} from './ui';
export function Settings({user,church,onUser,onRefresh,onLogout,onLink,onToast}:{user:Person;church:Church|null;onUser:(u:Person)=>void;onRefresh:()=>Promise<void>;onLogout:()=>void;onLink:(link:string)=>void;onToast:(s:string)=>void}){
 const [privacy,setPrivacy]=useState<Privacy>(user.privacy),[prefs,setPrefs]=useState<Preferences>(user.preferences),[available,setAvailable]=useState(user.available),[blocks,setBlocks]=useState<{user_id:string;name:string}[]>([]);
 useEffect(()=>{api<{user_id:string;name:string}[]>('/blocks').then(setBlocks).catch(e=>onToast(e.message))},[]);
 const tags=(value:string)=>value.split(',').map(v=>v.trim()).filter(Boolean);
 return <div className="settings-grid"><section className="panel"><h2><UserRound size={22}/> Help people know you.</h2><p>A few details can turn a familiar face into someone your church family knows.</p><Form submit="Save my profile" onSubmit={async data=>{const result=await api<Person>('/auth/profile','PUT',{name:val(data,'name'),phone:val(data,'phone'),address:val(data,'address'),household:val(data,'household'),bio:val(data,'bio'),skills:tags(val(data,'skills')),resources:tags(val(data,'resources')),groups:tags(val(data,'groups')),available,privacy});onUser(result);onToast('Profile saved.');await onRefresh()}}>
 <Field label="Your name"><input name="name" defaultValue={user.name} required maxLength={120}/></Field><Field label="A little about you"><textarea name="bio" defaultValue={user.bio} maxLength={2000} placeholder="What do you enjoy? What would you love to connect over?"/></Field><Field label="Household (optional)" hint="Share first names or a simple description if you wish. Avoid children’s birthdays or school details."><input name="household" defaultValue={user.household} maxLength={500}/></Field><div className="form-grid"><Field label="Phone"><input type="tel" name="phone" defaultValue={user.phone} maxLength={50}/></Field><Field label="Address"><input name="address" defaultValue={user.address} maxLength={500}/></Field></div>
 <Field label="Skills I can offer" hint="Separate with commas."><input name="skills" defaultValue={user.skills.join(', ')} placeholder="Piano lessons, babysitting, plumbing…"/></Field><Field label="Things I can lend or help with" hint="Separate with commas. Sharing a resource doesn’t commit you to every request."><input name="resources" defaultValue={user.resources.join(', ')} placeholder="Pickup truck, trailer, tools…"/></Field><Field label="My groups / seasons of life" hint="For directory filters; these tags do not limit who can see your profile."><input name="groups" defaultValue={user.groups.join(', ')} placeholder="Undergrads, Families, Tuesday life group…"/></Field><Check label="I’m currently open to lending a hand" checked={available} onChange={setAvailable}/>
 <h3><ShieldCheck size={19}/> You choose what is shared.</h3><p className="subtle">These choices apply to approved members of your churches. Your account email remains private unless you share it.</p>{(['directory','email','phone','address','household'] as (keyof Privacy)[]).map(k=><Check key={k} label={k==='directory'?'Show me in the directory':`Share my ${k}`} checked={privacy[k]} onChange={v=>setPrivacy({...privacy,[k]:v})}/>)}</Form></section>
 <div><section className="panel"><h2><Bell size={22}/> Care at your pace.</h2><p>Choose what you hear about and where. Email and push are off until you turn them on.</p><Form submit="Save notification choices" onSubmit={async()=>{
  if(prefs.push&&native()){const health=await api<{push_configured:boolean}>('/health');if(!health.push_configured)throw new Error('Push delivery has not been configured yet. Use email or your inbox for now.');await enablePush(onLink)}
  else if(!prefs.push&&user.preferences.push)await disablePush();
  const u=await api<Person>('/auth/preferences','PUT',prefs);onUser(u);onToast('Notification choices saved.');
 }}>
 <h3>I’d like to hear about</h3>{([['events','Events & everyday invitations'],['needs','Practical needs & helping hands'],['meals','Meal trains'],['community','Membership & community updates'],['reminders','Reminders for my commitments']] as [keyof Preferences,string][]).map(([k,label])=><Check key={k} label={label} checked={prefs[k]} onChange={v=>setPrefs({...prefs,[k]:v})}/>)}
 <h3>Send updates to</h3><Check label="My Village inbox" checked={prefs.in_app} onChange={v=>setPrefs({...prefs,in_app:v})}/><Check label="Email" checked={prefs.email} onChange={v=>setPrefs({...prefs,email:v})}/>{native()?<Check label="Phone push notifications" checked={prefs.push} onChange={v=>setPrefs({...prefs,push:v})}/>:<p className="subtle">Phone push notifications are available in the iOS and Android apps.</p>}<p className="subtle">Reminders also respect the category you’ve selected. Password-reset and verification emails always arrive when you request them.</p></Form></section>
 <section className="panel"><h3>Account & privacy</h3><p>{user.email}</p><button className="secondary" onClick={async()=>{try{await download(JSON.stringify(await api('/auth/export'),null,2),'village-my-data.json','application/json')}catch(e){onToast(e instanceof Error?e.message:'Unable to export.')}}}><Download size={16}/> Download my data</button>
 {church&&<button className="text-button danger" onClick={async()=>{if(confirm(`Leave ${church.name}? Your upcoming RSVPs, volunteer places, and undelivered meals will be released.`)){try{await api(`/churches/${church.id}/leave`,'POST');await onRefresh()}catch(e){onToast(e instanceof Error?e.message:'Unable to leave.')}}}}>Leave this church</button>}
 <details><summary>Delete my account</summary><p>This removes your profile, authored posts and commitments. A church owner must transfer ownership or delete the church first. Backups expire according to the operator’s retention policy.</p><Form submit="Permanently delete account" onSubmit={async data=>{if(!confirm('Permanently delete your account and authored content?'))return;await api('/auth/account','DELETE',{password:val(data,'password')});await storeSession();onLogout()}}><Field label="Confirm your password"><input name="password" type="password" required autoComplete="current-password"/></Field></Form></details>
 </section><section className="panel"><h3>Blocked members</h3>{!blocks.length&&<p className="subtle">No blocked members.</p>}{blocks.map(b=><div className="member-row" key={b.user_id}><span>{b.name}</span><button className="text-button" onClick={async()=>{await api('/blocks/'+b.user_id,'DELETE');setBlocks(blocks.filter(x=>x.user_id!==b.user_id));await onRefresh()}}>Unblock</button></div>)}</section></div></div>
}
