import {useState,useEffect,useRef,type ReactNode,type FormEvent} from 'react';
import {X,Heart,ArrowRight} from 'lucide-react';
export function Brand(){return <div className="brand"><span className="brand-mark"><Heart size={22}/></span><span>Village<span className="brand-sub">life, together.</span></span></div>}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}) {return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Check({label,checked,onChange,hint}:{label:string;checked:boolean;onChange:(v:boolean)=>void;hint?:string}) {return <label className="check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}{hint&&<small>{hint}</small>}</span></label>}
export function Empty({title,text,action}:{title:string;text:string;action?:ReactNode}){return <div className="empty"><Heart size={28}/><h3>{title}</h3><p>{text}</p>{action}</div>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {const ref=useRef<HTMLElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement;const el=ref.current;const focus=()=>Array.from(el?.querySelectorAll<HTMLElement>('button,input,textarea,select,a[href]')||[]).filter(e=>!e.hasAttribute('disabled'));focus()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const elements=focus(),first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;previous?.focus()}},[]);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section ref={ref} className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X/></button></header>{children}</section></div>}
export function Form({children,onSubmit,submit='Save',extra}:{children:ReactNode;onSubmit:(data:FormData)=>Promise<void>;submit?:string;extra?:ReactNode}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function handle(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;setBusy(true);setError('');try{await onSubmit(new FormData(form))}catch(ex){setError(ex instanceof Error?ex.message:'Please try again.')}finally{setBusy(false)}}
 return <form onSubmit={handle}>{children}{error&&<div role="alert" className="error">{error}</div>}<div className="form-actions"><button type="submit" className="primary" disabled={busy}>{busy?'Working…':submit}<ArrowRight size={16}/></button>{extra}</div></form>
}
export const val=(data:FormData,key:string)=>String(data.get(key)||'');
export const num=(data:FormData,key:string,fallback=0)=>Number(data.get(key)||fallback);
export function Avatar({name}:{name:string}){return <span className="avatar" aria-hidden="true">{name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span>}
