'use client';
import {useState,useEffect,useRef} from 'react';
import {Home,Users,CalendarDays,HandHeart,Utensils,Bell,Settings as SettingsIcon,ShieldCheck,LogOut,Plus,ArrowLeft,ArrowRight,Heart,CheckCircle,HelpCircle,RefreshCw,MoreHorizontal,UserRound} from 'lucide-react';
import type {View,Kind,Person,Church,Item,ChurchEvent,Need,MealTrain,Notice,Commitments} from '@/lib/types';
import {api,ApiError,loadSession,storeSession,enablePush,native} from '@/lib/api';
import {calendarDate,eventDate} from '@/lib/dates';
import {Auth,JoinChurch} from './Auth';
import {ItemForm} from './ItemForms';
import {ItemCard,Directory,Detail} from './Community';
import {Settings} from './Settings';
import {Admin} from './Admin';
import {Brand,Empty,Modal,Form,Field,val} from './ui';
const navItems:[View,string,typeof Home][]=[['home','Your Village',Home],['directory','People & resources',Users],['events','Life together',CalendarDays],['needs','Helping hands',HandHeart],['meals','Meal trains',Utensils],['commitments','My commitments',CheckCircle],['profile','My profile',UserRound]];
const meta:Record<View,[string,string]>={home:['Welcome home.','Little invitations. Practical care. People who show up.'],directory:['Your church family.','Find a familiar face, a helping hand, or something you can borrow.'],events:['Life is better, together.','Dinner, game night, a sideline cheer. Make an invitation.'],needs:['It’s okay to need a hand.','Someone may be waiting for a chance to help.'],meals:['Care around the table.','A warm meal. One less thing to carry.'],commitments:['The ways you’re showing up.','Your invitations, helping hands, and meal commitments in one place.'],inbox:['A little heads-up.','Updates from your church community, at your pace.'],profile:['Help people know you.','A few details can turn a familiar face into someone your church family knows.'],settings:['Make yourself at home.','Your profile, privacy, and notification choices.'],admin:['Help your Village flourish.','Welcome members, share invitations, and care for your community.'],help:['A simple place to belong.','Village removes a few steps between caring and showing up.']};
const isKind=(v:string):v is Kind=>['events','needs','meals'].includes(v);
const blank:Commitments={events:[],needs:[],meals:[]};
export default function VillageApp(){
 const [user,setUser]=useState<Person|null>(null),[boot,setBoot]=useState(true),[churches,setChurches]=useState<Church[]>([]),[churchId,setChurchId]=useState(''),[joinScreen,setJoinScreen]=useState(false),[invite,setInvite]=useState('');
 const [view,setView]=useState<View>('home'),[detailId,setDetailId]=useState(''),[detail,setDetail]=useState<Item|null>(null),[detailLoading,setDetailLoading]=useState(false);
 const [people,setPeople]=useState<Person[]>([]),[events,setEvents]=useState<ChurchEvent[]>([]),[needs,setNeeds]=useState<Need[]>([]),[meals,setMeals]=useState<MealTrain[]>([]),[notices,setNotices]=useState<Notice[]>([]),[commitments,setCommitments]=useState<Commitments>(blank),[loading,setLoading]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
 const [mobileMenu,setMobileMenu]=useState(false),[authKey,setAuthKey]=useState(0);
 const nativeLink=useRef<(url:string)=>void>(()=>{});
 const [editor,setEditor]=useState<{kind:Kind;item?:Item}|null>(null),[report,setReport]=useState<{kind:Kind|'directory'|'comments';id:string}|null>(null),[archive,setArchive]=useState(false),[audience,setAudience]=useState(''),[needCategory,setNeedCategory]=useState('');
 const generation=useRef(0),detailGeneration=useRef(0),inviteTried=useRef(''),onboarding=useRef(false);
 const church=churches.find(c=>c.id===churchId&&c.status==='approved')||null;
 function signedIn(person:Person,isNew=false){onboarding.current=isNew;setUser(person);if(isNew){sessionStorage.removeItem('village-onboarding-email');navigate('profile')}}
 function tell(message:string){setToast(message)}
 function navigate(v:View,id='',c=churchId){setMobileMenu(false);setView(v);setDetailId(id);setDetail(null);setError('');setEditor(null);setReport(null);if(c){setChurchId(c);localStorage.setItem('village-church',c)}setJoinScreen(false);const q=new URLSearchParams({view:v});if(id)q.set('id',id);if(c)q.set('church',c);history.pushState(null,'','/?'+q);window.scrollTo({top:0,behavior:'smooth'})}
 function followLink(link:string){const p=new URL(link,location.origin).searchParams;const v=p.get('view') as View;const c=p.get('church')||churchId;if(c&&!churches.some(x=>x.id===c&&x.status==='approved')){tell('This link is for a church you have not joined. Ask for its invitation first.');return}navigate(v in meta?v:'home',p.get('id')||'',c)}
 nativeLink.current=followLink;
 async function loadChurches(){const cs=await api<Church[]>('/churches/mine');setChurches(cs);setChurchId(current=>cs.some(c=>c.id===current&&c.status==='approved')?current:cs.find(c=>c.status==='approved')?.id||'');}
 function clear(){generation.current++;detailGeneration.current++;setPeople([]);setEvents([]);setNeeds([]);setMeals([]);setCommitments(blank);setNotices([]);setDetail(null)}
 async function dataLoad(c=churchId){
  if(!c)return;const gen=++generation.current;setLoading(true);setError('');
  try{const root=`/churches/${c}`;const [p,e,n,m,k,i]=await Promise.all([api<Person[]>(root+'/directory'),api<ChurchEvent[]>(root+'/events'+(archive?'?archive=true':'')),api<Need[]>(root+'/needs'),api<MealTrain[]>(root+'/meals'),api<Commitments>(root+'/commitments'),api<Notice[]>('/notifications')]);if(gen!==generation.current)return;setPeople(p);setEvents(e);setNeeds(n);setMeals(m);setCommitments(k);setNotices(i)}catch(ex){if(gen!==generation.current)return;if(ex instanceof ApiError&&ex.status===401){clear();setUser(null);await storeSession();}else if(ex instanceof ApiError&&ex.status===403){clear();await loadChurches();setError(ex.message)}else setError(ex instanceof Error?ex.message:'Connection failed. Please try again.')}finally{if(gen===generation.current)setLoading(false)}
 }
 async function detailLoad(){if(!church||!detailId||!isKind(view))return;const gen=++detailGeneration.current;setDetailLoading(true);try{const d=await api<Item>(`/churches/${church.id}/${view}/${detailId}`);if(gen===detailGeneration.current)setDetail(d)}catch(e){if(gen===detailGeneration.current)setError(e instanceof Error?e.message:'Unable to load details.')}finally{if(gen===detailGeneration.current)setDetailLoading(false)}}
 async function refresh(){await loadChurches();if(church){await dataLoad();if(detailId)await detailLoad()}}
 useEffect(()=>{let active=true;const q=new URLSearchParams(location.search);const v=q.get('view');if(v&&v in meta)setView(v as View);setDetailId(q.get('id')||'');setChurchId(q.get('church')||localStorage.getItem('village-church')||'');const code=q.get('join')||sessionStorage.getItem('village-invite')||'';setInvite(code);if(code)sessionStorage.setItem('village-invite',code);
  if(q.get('action')==='verify'){setBoot(false);return()=>{active=false};}
  loadSession().then(()=>api<Person>('/auth/me')).then(u=>{if(active)setUser(u)}).catch(e=>{if(active&&!(e instanceof ApiError&&e.status===401))setError(e.message)}).finally(()=>{if(active)setBoot(false)});
  return()=>{active=false};
 },[]);
 useEffect(()=>{if(!user)return;loadChurches().catch(e=>setError(e.message));},[user?.id]);
 useEffect(()=>{if(!user||!invite||inviteTried.current===user.id+invite)return;inviteTried.current=user.id+invite;api<Church>('/churches/join','POST',{code:invite}).then(async c=>{sessionStorage.removeItem('village-invite');setInvite('');await loadChurches();if(c.status==='approved')navigate(onboarding.current?'profile':'home','',c.id);else{setJoinScreen(true);tell('Your church connection is saved. An administrator will approve your access.')}}).catch(e=>{tell(e.message);setJoinScreen(true)});},[user?.id,invite]);
 useEffect(()=>{clear();setAudience('');setNeedCategory('');if(user&&church)void dataLoad(church.id);},[user?.id,church?.id,archive]);
 useEffect(()=>{setDetail(null);detailGeneration.current++;if(detailId&&church&&isKind(view))void detailLoad()},[church?.id,detailId,view]);
 useEffect(()=>{const onPop=()=>{const q=new URLSearchParams(location.search);const v=q.get('view') as View;setView(v in meta?v:'home');setDetailId(q.get('id')||'');if(q.get('church'))setChurchId(q.get('church')!)};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);
 useEffect(()=>{if(!native())return;let remove:(()=>void)|undefined;import('@capacitor/app').then(async({App})=>{const handle=(url:string)=>{const p=new URL(url).searchParams;if(['verify','reset'].includes(p.get('action')||'')){clear();history.replaceState(null,'','/?'+p.toString());setUser(null);setAuthKey(k=>k+1);return}if(p.get('join')){inviteTried.current='';setInvite(p.get('join')!);sessionStorage.setItem('village-invite',p.get('join')!)}else nativeLink.current(url)};const launch=await App.getLaunchUrl();if(launch)handle(launch.url);const listener=await App.addListener('appUrlOpen',e=>handle(e.url));remove=()=>void listener.remove()});return()=>remove?.()},[]);
 useEffect(()=>{if(user?.preferences.push&&native())enablePush(followLink).catch(e=>tell(e.message));},[user?.id]);
 useEffect(()=>{if(!user)return;const handler=()=>{if(document.visibilityState==='visible'&&church)void dataLoad()};document.addEventListener('visibilitychange',handler);return()=>document.removeEventListener('visibilitychange',handler)},[user?.id,church?.id]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(timer)},[toast]);
 async function logout(){try{await api('/auth/logout','POST')}catch{}await storeSession();clear();setUser(null);setChurches([]);setChurchId('');history.replaceState(null,'','/');}
 if(boot)return <div className="boot"><Brand/><p>Making room for you…</p></div>;
 if(!user)return <><Auth key={authKey} onLogin={signedIn} invite={invite} onClearInvite={()=>{setInvite('');sessionStorage.removeItem('village-invite');inviteTried.current='';history.replaceState(null,'','/')}}/>{error&&<div className="error auth-error">{error}</div>}<footer className="auth-footer"><a href="/privacy.html">Privacy</a><a href="/terms.html">Community terms</a></footer></>;
 const unread=notices.filter(n=>!n.read).length;
 const renderNav=(mobile=false)=>navItems.filter(([v])=>!mobile||['home','directory','events','needs','meals'].includes(v)).map(([v,label,Icon])=><button key={v} className={view===v&&!joinScreen?'active':''} onClick={()=>navigate(v)} disabled={!church&&v!=='profile'}><Icon size={20}/><span>{mobile?({home:'Home',directory:'People',events:'Invites',needs:'Help',meals:'Meals'} as Record<string,string>)[v]:label}</span></button>);
 const open=(kind:Kind,id:string)=>navigate(kind,id);
 const create=(kind:Kind)=>setEditor({kind});
 const latest=church&&<><div className="home-hero"><span className="eyebrow">{church.name}</span><h1>A church family<br/><em>to do life with.</em></h1><p>Hi {user.name.split(' ')[0]}. There’s a place for you at the table.</p><button className="primary" onClick={()=>create('events')}>Make an invitation <ArrowRight size={17}/></button><span className="hero-flower" aria-hidden="true"><Heart size={120}/></span></div>
 <div className="home-shortcuts"><button onClick={()=>navigate('directory')}><Users/><strong>{people.length} familiar faces</strong><span>Get to know your people</span></button><button onClick={()=>navigate('needs')}><HandHeart/><strong>{needs.filter(n=>n.status==='open'&&n.volunteer_count<n.volunteers_needed).length} ways to help</strong><span>A little care goes a long way</span></button><button onClick={()=>navigate('commitments')}><CheckCircle/><strong>{commitments.events.length+commitments.needs.length+commitments.meals.length} commitments</strong><span>Your next ways to show up</span></button></div>
 {!user.bio&&!user.skills.length&&!user.resources.length&&<div className="welcome-note"><div><strong>Let your church family know you.</strong><p>Add a little about yourself and what you’re happy to share. You control your contact details.</p></div><button className="secondary" onClick={()=>navigate('profile')}>Set up my profile</button></div>}
 <div className="section-line"><h2>There’s room for you.</h2><button className="text-button" onClick={()=>navigate('events')}>All invitations <ArrowRight size={15}/></button></div><div className="card-grid">{events.slice(0,3).map(e=><ItemCard key={e.id} item={e} kind="events" church={church} onOpen={()=>open('events',e.id)}/>)}</div>{!events.length&&<Empty title="Ordinary life counts, too." text="A walk, a meal, a kid’s game. Your first invitation could be someone else’s first connection." action={<button className="secondary" onClick={()=>create('events')}>Invite someone in</button>}/>}
 <div className="section-line"><h2>A little help, a lot of love.</h2><button className="text-button" onClick={()=>navigate('meals')}>Meal trains <ArrowRight size={15}/></button></div><div className="card-grid">{meals.filter(m=>!m.closed&&m.claimed_count<m.slot_count).slice(0,2).map(m=><ItemCard key={m.id} item={m} kind="meals" church={church} onOpen={()=>open('meals',m.id)}/>)}{needs.filter(n=>n.status==='open'&&n.volunteer_count<n.volunteers_needed).slice(0,2).map(n=><ItemCard key={n.id} item={n} kind="needs" church={church} onOpen={()=>open('needs',n.id)}/>)}</div></>;
 return <div className="app"><aside className="sidebar"><Brand/><div className="church-switch"><label htmlFor="church-switch">Your church community</label><select id="church-switch" value={joinScreen?'join':churchId} onChange={e=>{clear();if(e.target.value==='join')setJoinScreen(true);else navigate('home','',e.target.value)}}>{churches.filter(c=>c.status==='approved').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}<option value="join">Join / set up a church</option></select></div><nav aria-label="Main navigation">{renderNav()}</nav><div className="sidebar-bottom"><button onClick={()=>navigate('help')}><HelpCircle size={20}/> How Village works</button>{church&&church.role!=='member'&&<button className={view==='admin'?'active':''} onClick={()=>navigate('admin')}><ShieldCheck size={20}/> Church admin</button>}<button onClick={()=>navigate('settings')}><SettingsIcon size={20}/> My settings</button><button onClick={()=>void logout()}><LogOut size={20}/> Sign out</button></div><p className="sidebar-note">A shared place.<br/>A life shared.</p></aside>
 <div className="app-body"><header className="topbar"><div className="mobile-brand"><Brand/></div><span className="desktop-greeting">{church?.name||'Your Village'}</span><div className="topbar-actions"><button aria-label={`Notifications${unread?`, ${unread} unread`:''}`} onClick={()=>navigate('inbox')}><Bell size={21}/>{unread>0&&<span className="count">{unread}</span>}</button><button aria-label="My commitments" className="mobile-only" onClick={()=>navigate('commitments')}><CheckCircle size={21}/></button><button aria-label="My settings" onClick={()=>navigate('settings')}><SettingsIcon size={21}/></button><button className="mobile-only" aria-label="More options" aria-expanded={mobileMenu} onClick={()=>setMobileMenu(s=>!s)}><MoreHorizontal size={21}/></button></div>{mobileMenu&&<div className="mobile-menu"><button onClick={()=>navigate('profile')}><UserRound size={18}/> My profile</button><button onClick={()=>navigate('settings')}><SettingsIcon size={18}/> My settings</button><button onClick={()=>navigate('commitments')}><CheckCircle size={18}/> My commitments</button>{church&&church.role!=='member'&&<button onClick={()=>navigate('admin')}><ShieldCheck size={18}/> Church administration</button>}<button onClick={()=>{setMobileMenu(false);setJoinScreen(true)}}><Users size={18}/> Join / switch church</button><button onClick={()=>navigate('help')}><HelpCircle size={18}/> How Village works</button><button onClick={()=>void logout()}><LogOut size={18}/> Sign out</button></div>}</header>
 <main className="main-content"><a className="skip-link" href="#page-content">Skip to content</a><div id="page-content">
 {joinScreen||(!church&&!['profile','settings','help','inbox'].includes(view))?<JoinChurch churches={churches} invite={invite} onRefresh={loadChurches} onSelect={id=>navigate(onboarding.current?'profile':'home','',id)}/>:
 <>{view!=='home'&&!detailId&&<div className="page-heading"><span className="eyebrow">{church?.name||'Your Village'}</span><h1>{meta[view][0]}</h1><p>{meta[view][1]}</p></div>}{error&&<div className="error" role="alert">{error}<button onClick={()=>void refresh()}><RefreshCw size={15}/> Try again</button></div>}
 {detailId&&isKind(view)&&church?<><button className="text-button back" onClick={()=>navigate(view)}><ArrowLeft size={16}/> Back to {view==='events'?'invitations':view==='needs'?'helping hands':'meal trains'}</button>{detailLoading&&!detail?<p role="status">Loading details…</p>:detail&&<Detail kind={view} item={detail} church={church} user={user} onRefresh={refresh} onEdit={()=>setEditor({kind:view,item:detail})} onDelete={async()=>{if(confirm('Delete this post and its commitments? Participants will receive a cancellation update.')){try{await api(`/churches/${church.id}/${view}/${detail.id}`,'DELETE');navigate(view);await dataLoad()}catch(e){tell(e instanceof Error?e.message:'Unable to delete.')}}}} onReport={(kind,id)=>setReport({kind,id})} onToast={tell}/>}</>:
 <>{loading&&<div className="loading-bar" role="status">Refreshing your Village…</div>}{view==='home'&&latest}
 {view==='directory'&&<Directory people={people} onReport={id=>setReport({kind:'directory',id})} onBlock={async id=>{if(church&&confirm('Block this member? You will no longer see one another’s directory entry or authored posts.')){try{await api(`/churches/${church.id}/blocks/${id}`,'PUT');await dataLoad();tell('Member blocked. You can undo this in Settings.')}catch(e){tell(e instanceof Error?e.message:'Unable to block.')}}}}/>}
 {isKind(view)&&church&&<><div className="list-toolbar"><div className="filters">{view==='events'&&<><select aria-label="Event audience" value={audience} onChange={e=>setAudience(e.target.value)}><option value="">All invitations</option>{[...new Set(events.flatMap(e=>e.audience))].map(a=><option key={a}>{a}</option>)}</select><label className="inline-check"><input type="checkbox" checked={archive} onChange={e=>setArchive(e.target.checked)}/> Past events</label></>}{view==='needs'&&<select aria-label="Need category" value={needCategory} onChange={e=>setNeedCategory(e.target.value)}><option value="">All needs</option>{[...new Set(needs.map(n=>n.category))].map(c=><option key={c}>{c}</option>)}</select>}</div><button className="primary" onClick={()=>create(view)}><Plus size={17}/>{view==='events'?'Make an invitation':view==='needs'?'Ask for help':'Start a meal train'}</button></div><div className="card-grid">{(view==='events'?events.filter(e=>!audience||e.audience.includes(audience)):view==='needs'?needs.filter(n=>!needCategory||n.category===needCategory):meals).map(item=><ItemCard key={item.id} kind={view} item={item} church={church} onOpen={()=>open(view,item.id)}/>)}</div>{!(view==='events'?events.length:view==='needs'?needs.length:meals.length)&&!loading&&<Empty title={view==='events'?'Start something ordinary.':view==='needs'?'No one has to do it all alone.':'A meal can say so much.'} text={view==='events'?'Invite your church family into something you’re already doing.':view==='needs'?'Ask for a hand or post a need for someone who gave you permission.':'Organize care for a new baby, recovery, or a difficult season.'}/>}</>}
 {view==='commitments'&&church&&<><div className="commitment-group"><h2>Meals I’m bringing</h2>{commitments.meals.map(({slot,train})=><button className="commitment-card" key={slot.id} onClick={()=>open('meals',train.id)}><Utensils/><div><strong>{train.title}</strong><p>{calendarDate(slot.date,true)} · {train.delivery_window}</p><small>{slot.meal}</small>{train.closed&&<span className="badge">Train closed — contact organizer</span>}</div><ArrowRight size={18}/></button>)}</div><div className="commitment-group"><h2>Invitations I’ve accepted</h2>{commitments.events.map(e=><button className="commitment-card" key={e.id} onClick={()=>open('events',e.id)}><CalendarDays/><div><strong>{e.title}</strong><p>{eventDate(e.starts_at,church.timezone)}{e.cancelled?' · Cancelled':''}</p></div><ArrowRight size={18}/></button>)}</div><div className="commitment-group"><h2>Where I’m lending a hand</h2>{commitments.needs.map(n=><button className="commitment-card" key={n.id} onClick={()=>open('needs',n.id)}><HandHeart/><div><strong>{n.title}</strong><p>{n.due_date?calendarDate(n.due_date,true):n.category}</p></div><ArrowRight size={18}/></button>)}</div>{!commitments.meals.length&&!commitments.events.length&&!commitments.needs.length&&<Empty title="There’s a place for you." text="Accept an invitation, lend a hand, or bring a meal. Your commitments will appear here."/>}</>}
 {view==='inbox'&&<><div className="section-line"><span>{unread} unread updates</span><button className="text-button" onClick={async()=>{await api('/notifications/read','POST');if(church)await dataLoad()}}>Mark all read</button></div>{notices.map(n=><button key={n.id} className={'notice '+(n.read?'':'unread')} onClick={async()=>{try{await api(`/notifications/${n.id}/read`,'POST');setNotices(notices.map(i=>i.id===n.id?{...i,read:true}:i));followLink(n.link)}catch(e){tell(e instanceof Error?e.message:'Unable to open.')}}}><span className="eyebrow">{n.category} · {new Date(n.created_at).toLocaleDateString()}</span><h3>{n.title}</h3><p>{n.body}</p></button>)}{!notices.length&&<Empty title="A quiet moment." text="Your selected community updates will appear here. Choose what you receive in Settings."/>}</>}
 {view==='profile'&&onboarding.current&&<div className="welcome-note"><div><strong>Welcome! Let your church family know you.</strong><p>Everything beyond your name is optional. You choose which details to share.</p></div><button className="secondary" onClick={()=>{onboarding.current=false;if(church)navigate('home');else setJoinScreen(true)}}>I’ll do this later</button></div>}
 {['profile','settings'].includes(view)&&<Settings profileOnly={view==='profile'} onProfileSaved={()=>{if(onboarding.current){onboarding.current=false;if(church)navigate('home');else setJoinScreen(true)}}} key={user.id} user={user} church={church} onUser={setUser} onRefresh={refresh} onLogout={()=>{clear();setUser(null)}} onLink={followLink} onToast={tell}/>}
 {view==='admin'&&church&&(church.role==='member'?<Empty title="For your church team" text="Church administrators manage membership and invitations here."/>:<Admin key={church.id} church={church} onRefresh={refresh} onToast={tell} onOpen={open}/>)}
 {view==='help'&&<div className="help-grid">{[['People & resources','Search a name, skill, or something useful—like a truck. Your profile lets you choose which contact and household details your church can see.'],['Life together','Invite people into ordinary life: a meal, a walk, a game, a concert. RSVP with a guest count. Tags help members find invitations for their season of life.'],['Helping hands','Ask for practical help. Offer a hand. An organizer can post on behalf of someone else with permission, so participation doesn’t depend on everyone using an app.'],['Meal trains','Choose the actual meal dates, review dietary needs, claim a date, and write what you’re bringing. You can edit, cancel, or mark the meal delivered.'],['My commitments','See all the ways you’ve agreed to show up. If plans change, open the item and cancel so the organizer knows.'],['Privacy & peace','Every private screen requires an approved church connection. Change notifications and privacy in Settings. Report concerns from a post or directory entry.']].map(([title,text])=><section key={title} className="panel"><h3>{title}</h3><p>{text}</p></section>)}<section className="panel"><h3>Your church connection</h3><p>Use your church’s code, invitation link, or QR code. Invitations connect you directly. Requests made through church search need approval.</p><button className="secondary" onClick={()=>setJoinScreen(true)}>Join another church</button></section></div>}
 </>}
 </>}
 </div><footer><span>Village · life, together.</span><div><a href="/privacy.html" target="_blank" rel="noreferrer">Privacy</a><a href="/terms.html" target="_blank" rel="noreferrer">Community terms</a><button className="text-button" onClick={()=>navigate('help')}>Help</button></div></footer></main></div><nav className="mobile-nav" aria-label="Mobile navigation">{renderNav(true)}</nav>
 {toast&&<div className="toast" role="status">{toast}<button aria-label="Dismiss message" onClick={()=>setToast('')}>×</button></div>}
 {editor&&church&&<Modal title={editor.item?'Edit details':editor.kind==='events'?'Make an invitation':editor.kind==='needs'?'Ask for a helping hand':'Start a meal train'} onClose={()=>{if(confirm('Close this form? Unsaved changes will be lost.'))setEditor(null)}}><ItemForm kind={editor.kind} church={church} item={editor.item} onSaved={async()=>{setEditor(null);tell('Saved. Thank you for bringing your Village together.');await refresh()}}/></Modal>}
 {report&&church&&<Modal title="Share a concern" onClose={()=>setReport(null)}><p>Your church team will review this privately.</p><Form submit="Send report" onSubmit={async data=>{await api(`/churches/${church.id}/reports`,'POST',{kind:report.kind,target_id:report.id,reason:val(data,'reason')});setReport(null);tell('Report sent to your church administrators.')}}><Field label="What should the church team know?"><textarea name="reason" minLength={5} maxLength={1500} required/></Field></Form></Modal>}
 </div>
}
