import {chromium} from 'playwright';

import fs from 'node:fs';
import path from 'node:path';
const output=process.env.VILLAGE_SCREENSHOT_DIR||'test-output';fs.mkdirSync(output,{recursive:true});
(async()=>{
const browser=await chromium.launch({...(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH}:{}),headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const testTitle='Browser tested meal train '+Date.now();
const errors=[];page.on('pageerror',err=>errors.push(err.message));
await page.goto(process.env.VILLAGE_TEST_URL||'http://localhost:8000');
await page.getByLabel('Email address').fill('pastor@example.org');
await page.getByLabel('Password',{exact:true}).fill('Village-demo-only-2026!');
await page.getByRole('button',{name:'Sign in',exact:true}).click();
await page.getByRole('heading',{name:'A church family to do life with.'}).waitFor();
await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
await page.getByRole('button',{name:'Meal trains',exact:true}).first().click();
await page.getByRole('button',{name:'Start a meal train',exact:true}).click();
await page.getByLabel('Meal train title').fill(testTitle);
await page.getByLabel('Who are the meals for?').fill('Example family');
await page.getByLabel('First date').fill('2027-03-08');
await page.getByLabel('Last date').fill('2027-03-21');
await page.getByRole('button',{name:'Tue',exact:true}).click();
await page.getByRole('button',{name:'Fri, Mar 12',exact:true}).click();
await page.getByLabel('These are the exact dates I want available.').check();
await page.getByLabel('I am the recipient or have their permission to share these details.').check();
await page.getByRole('dialog').screenshot({path:path.join(output,'meal-setup.png')});
const creation=page.waitForResponse(r=>r.url().endsWith('/meals')&&r.request().method()==='POST');
await page.getByRole('dialog').getByRole('button',{name:'Start meal train',exact:true}).click();
const response=await creation;if(response.status()!==201)throw new Error(await response.text());
const created=await response.json();
const expected=['2027-03-08','2027-03-09','2027-03-10','2027-03-15','2027-03-16','2027-03-17','2027-03-19'];
if(JSON.stringify(created.slots.map(s=>s.date))!==JSON.stringify(expected))throw new Error('Browser dates differ: '+JSON.stringify(created.slots));
await page.getByRole('dialog').waitFor({state:'hidden'});
await page.getByRole('button',{name:new RegExp(testTitle)}).click();
await page.getByRole('heading',{name:testTitle,exact:true}).waitFor();
await page.getByRole('button',{name:'Bring a meal',exact:true}).first().click();
await page.getByLabel('What meal are you bringing?').fill('Chicken soup, rolls, and fruit');
await page.getByRole('button',{name:'Confirm my meal',exact:true}).click();
await page.getByText('Chicken soup, rolls, and fruit',{exact:true}).waitFor();
await page.screenshot({path:path.join(output,'meal-detail.png'),fullPage:true});
await page.getByRole('button',{name:'My commitments',exact:true}).first().click();
await page.getByRole('button',{name:new RegExp(testTitle)}).waitFor();
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Home',exact:true}).click();
await page.getByRole('heading',{name:'A church family to do life with.'}).waitFor();
await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
if(overflow)throw new Error('Mobile horizontal overflow');
await page.getByRole('button',{name:'Meals',exact:true}).click();
await page.getByRole('button',{name:new RegExp(testTitle)}).click();
await page.screenshot({path:path.join(output,'mobile-meals.png'),fullPage:true});
if(errors.length)throw new Error(errors.join('\n'));
console.log('Browser smoke passed: desktop, mobile, exact date setup, meal claim text, commitments, no console errors or horizontal overflow.');
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
