import {native} from './api';
// Calendar dates stay strings. Never feed YYYY-MM-DD into a UTC/local conversion.
export function calendarDate(value:string,full=false) { const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d,12).toLocaleDateString(undefined,full?{weekday:'long',month:'long',day:'numeric',year:'numeric'}:{weekday:'short',month:'short',day:'numeric'}); }
export function eventDate(value:string,zone:string) {return new Date(value).toLocaleString(undefined,{timeZone:zone,weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
export function localInput(value?:string) { if(!value)return '';const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}` }
export function dateRange(start:string,end:string,weekdays:number[]) { if(!start||!end)return [];const a=start.split('-').map(Number),b=end.split('-').map(Number);const current=new Date(a[0],a[1]-1,a[2],12),last=new Date(b[0],b[1]-1,b[2],12);const list:string[]=[];while(current<=last&&list.length<367){if(weekdays.includes((current.getDay()+6)%7))list.push(`${current.getFullYear()}-${String(current.getMonth()+1).padStart(2,'0')}-${String(current.getDate()).padStart(2,'0')}`);current.setDate(current.getDate()+1);if((current.getTime()-new Date(a[0],a[1]-1,a[2],12).getTime())>367*86400000)break;}return list; }
export function todayDate() {const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export async function download(text:string,name:string,type='text/plain') {if(native()){const {Filesystem,Directory,Encoding}=await import('@capacitor/filesystem');const {Share}=await import('@capacitor/share');const result=await Filesystem.writeFile({path:name,data:text,directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:name,url:result.uri});return;}const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
export async function calendarFile(title:string,start:string,end:string|undefined,description:string,location:string) {
 const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
 const stamp=(s:string)=>new Date(s).toISOString().replace(/[-:]/g,'').replace(/\.\d+Z/,'Z');
 await download(['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Village//Community//EN','BEGIN:VEVENT',`UID:${crypto.randomUUID()}@village`,`DTSTAMP:${stamp(new Date().toISOString())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(end||new Date(new Date(start).getTime()+3600000).toISOString())}`,`SUMMARY:${escape(title)}`,`DESCRIPTION:${escape(description)}`,`LOCATION:${escape(location)}`,'END:VEVENT','END:VCALENDAR'].join('\r\n'),'village-event.ics','text/calendar');
}
